#!/usr/bin/python3
import sys


def factorize(num):
    for factor in range(2, num):
        if num % factor == 0:
            return factor, num // factor
    return None


def main(filename):
    try:
        with open(filename, "r") as f:
            for line in f:
                num = int(line.strip())
                factors = factorize(num)
                if factors:
                    p, q = factors
                    print(f"{num} = {p} * {q}")
                else:
                    print(f"{num} is a prime number")
    except FileNotFoundError:
        print(f"The file '{filename}' not found!")
    except ValueError:
        print("Please make sure that all lines contain valid numbers > 1")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit()

    filename = sys.argv[1]
    main(filename)
