#!/usr/bin/python3
import sys


def factorize(n):
    for factor in range(2, n):
        if n % factor == 0:
            return factor, n // factor
    return None


def main(filename):
    try:
        with open(filename, "r") as f:
            for line in f:
                n = int(line.strip())
                factors = factorize(n)
                if factors:
                    p, q = factors
                    print(f"{n}={p}*{q}")
                else:
                    print(f"{n} is a prime number")
    except FileNotFoundError:
        print(f"The file '{filename}' not found!")
    except ValueError:
        print("Please make sure that all lines contain valid numbers > 1")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit()

    filename = sys.argv[1]
    main(filename)
