#!/usr/bin/python3
import sys
import math


def factors(filename):
    with open(filename) as f:
        lines = f.readlines()

    numbers = [int(line.strip()) for line in lines]

    for n in numbers:
        for i in range(2, int(math.sqrt(n)) + 1):
            if n % i == 0:
                p = i
                q = n // i
                print(f"{n}={p}*{q}")
                break


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit()
    else:
        factors(sys.argv[1])
