#!/usr/bin/python3
import sys


def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True


def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            if is_prime(i) and is_prime(n // i):
                return i, n // i
    return None


def main(filename):
    try:
        with open(filename, 'r') as file:
            n = int(file.read().strip())
            factors = factorize(n)
            if factors:
                p, q = factors
                print(f"{n}={p}*{q}")
            else:
                print(f"{n} is a prime number")

    except FileNotFoundError:
        print(f"File '{filename}' not found.")
    except ValueError:
        print("Please make sure the file contains a valid natural number.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
    else:
        filename = sys.argv[1]
        main(filename)
